/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "var(--gray-a5)",
        input: "var(--gray-a5)",
        ring: "var(--green-7)",
        background: "var(--color-background)",
        foreground: "var(--gray-12)",
        primary: {
          DEFAULT: "var(--green-9)",
          foreground: "var(--green-contrast)",
        },
        secondary: {
          DEFAULT: "var(--green-3)",
          foreground: "var(--green-11)",
        },
        destructive: {
          DEFAULT: "var(--gray-8)",
          foreground: "var(--gray-contrast)",
        },
        success: {
          DEFAULT: "var(--green-7)",
          foreground: "var(--green-contrast)",
        },
        muted: {
          DEFAULT: "var(--gray-5)",
          foreground: "var(--gray-9)",
        },
        accent: {
          DEFAULT: "var(--green-a7)",
          foreground: "var(--green-contrast)",
        },
        popover: {
          DEFAULT: "var(--gray-surface)",
          foreground: "var(--gray-12)",
        },
        card: {
          DEFAULT: "var(--gray-surface)",
          foreground: "var(--gray-12)",
        },
        green: {
          1: "var(--green-1)",
          2: "var(--green-2)",
          3: "var(--green-3)",
          4: "var(--green-4)",
          5: "var(--green-5)",
          6: "var(--green-6)",
          7: "var(--green-7)",
          8: "var(--green-8)",
          9: "var(--green-9)",
          10: "var(--green-10)",
          11: "var(--green-11)",
          12: "var(--green-12)",
          contrast: "var(--green-contrast)",
          surface: "var(--green-surface)",
          indicator: "var(--green-indicator)",
          track: "var(--green-track)",
          a1: "var(--green-a1)",
          a2: "var(--green-a2)",
          a3: "var(--green-a3)",
          a4: "var(--green-a4)",
          a5: "var(--green-a5)",
          a6: "var(--green-a6)",
          a7: "var(--green-a7)",
          a8: "var(--green-a8)",
          a9: "var(--green-a9)",
          a10: "var(--green-a10)",
          a11: "var(--green-a11)",
          a12: "var(--green-a12)",
        },
        gray: {
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
          12: "var(--gray-12)",
          contrast: "var(--gray-contrast)",
          surface: "var(--gray-surface)",
          indicator: "var(--gray-indicator)",
          track: "var(--gray-track)",
          a1: "var(--gray-a1)",
          a2: "var(--gray-a2)",
          a3: "var(--gray-a3)",
          a4: "var(--gray-a4)",
          a5: "var(--gray-a5)",
          a6: "var(--gray-a6)",
          a7: "var(--gray-a7)",
          a8: "var(--gray-a8)",
          a9: "var(--gray-a9)",
          a10: "var(--gray-a10)",
          a11: "var(--gray-a11)",
          a12: "var(--gray-a12)",
        },
        "brand-green-dark": "#2E5939",
        "brand-orange-dark": "#D95829",
        "brand-orange-medium": "#F28157",
        "brand-orange-light": "#F29F80",
        "brand-off-white": "#F2F2F2",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
