    -- En project/supabase/migrations/20250521155339_create_travel_submissions_table_only.sql
    CREATE TABLE IF NOT EXISTS public.travel_data_submissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id UUID NOT NULL REFERENCES public.events(id) ON DELETE CASCADE, -- CAMBIADO A UUID
        user_type public.user_type_enum NOT NULL,
        total_hotel_nights INTEGER,
        comments TEXT,
        submitted_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
    );